### ISSUE TITLE
Action doesn't work with actions/checkout@v4

### ISSUE THREAD

**Issue by aaronczichon** [zwacky/goodreads-profile-workflow#12]
# Description

Your Action for Goodreads works not with the `actions/checkout@v4` version. It throws an error:
```
TypeError: Cannot read properties of undefined (reading 'channel')
```

# How to reproduce?

Change your workflow before calling the goodreads action your `actions/checkout@v2` to `actions/checkout@v4`.

**Comment by zwacky** [comment]
Hey @aaronczichon (and good to see you again),
I checked with `actions/checkout@v4` on my own [workflow file](https://github.com/zwacky/zwacky/actions/runs/10749073332/workflow) and it ran successfully.

I've seen your error message before in connection with either
- goodreads API is not responding
- the goodreads profile is not set to public

since your workflow runs correctly with `actions/checkout@v2` I think it's something different than the ones I listed. 🤔

**Comment by aaronczichon** [comment]
Yeah it works in a new repository with other shelf. This is an error that occurs sometimes. I'll investigate further :)

**Comment by hrmeetsingh** [comment]
Hi, I saw this happening today when using checkout@v4 and `goodreads-profile-workflow@v1.2.4`. initially looked like some issue with [this line](https://github.com/zwacky/goodreads-profile-workflow/blob/a1b8b48b991987cb356422d51fcc91a81a2b6e26/index.js#L32) but the code works fine when running locally. Adding comment to get the updates on this

**Comment by aaronczichon** [comment]
Yeah I sometimes have the issue also with `checkout@v2` and it occurs randomly. I have a sense that it's related to Goodreads issues. Maybe rate limit or something.
